name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CI_BOT_URL }}
      JOBS: 1
      NODE_OPTIONS: "--max_old_space_size=4096"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: setup chrome
        uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # latest
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ember-cli-deploy-rest-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ember-cli-deploy-rest-${{ matrix.node }}
      - name: npm install
        run: npm ci
      - name: npm lint
        run: npm run lint:js
      - name: npm test
        run: npm run test -- -r=dot
